package report

import (
	"context"
	"fmt"
	"io"

	"github.com/guimove/clusterfit/internal/model"
)

// MarkdownReporter outputs recommendations as a Markdown document.
type MarkdownReporter struct {
	w io.Writer
}

func (r *MarkdownReporter) Report(ctx context.Context, recs []model.Recommendation, meta ReportMeta) error {
	fmt.Fprintf(r.w, "# ClusterFit Recommendations\n\n")
	fmt.Fprintf(r.w, "| Property | Value |\n")
	fmt.Fprintf(r.w, "|----------|-------|\n")
	fmt.Fprintf(r.w, "| Cluster | %s |\n", meta.ClusterName)
	fmt.Fprintf(r.w, "| Region | %s |\n", meta.Region)
	fmt.Fprintf(r.w, "| Pods | %d (+ %d DaemonSets) |\n", meta.TotalPods, meta.TotalDaemons)
	fmt.Fprintf(r.w, "| Percentile | p%.0f |\n", meta.Percentile*100)
	fmt.Fprintf(r.w, "| Window | %s to %s |\n\n",
		meta.WindowStart.Format("2006-01-02"), meta.WindowEnd.Format("2006-01-02"))

	if len(recs) == 0 {
		fmt.Fprintf(r.w, "No recommendations available.\n")
		return nil
	}

	// Recommendations table
	fmt.Fprintf(r.w, "## Rankings\n\n")
	fmt.Fprintf(r.w, "| Rank | Configuration | Nodes | CPU%% | Mem%% | Score | $/month |\n")
	fmt.Fprintf(r.w, "|------|--------------|-------|------|------|-------|--------|\n")

	for _, rec := range recs {
		sr := rec.SimulationResult
		fmt.Fprintf(r.w, "| %d | %s | %d | %.1f%% | %.1f%% | %.1f | $%.0f |\n",
			rec.Rank,
			sr.InstanceConfig.Label(),
			sr.TotalNodes,
			sr.AvgCPUUtilization*100,
			sr.AvgMemUtilization*100,
			rec.OverallScore,
			rec.MonthlyCost,
		)
	}

	// Top recommendation detail
	top := recs[0]
	topSR := top.SimulationResult
	fmt.Fprintf(r.w, "\n## Top Recommendation\n\n")
	fmt.Fprintf(r.w, "**%s**\n\n", topSR.InstanceConfig.Label())
	fmt.Fprintf(r.w, "- Nodes: %d\n", topSR.TotalNodes)
	fmt.Fprintf(r.w, "- Monthly cost: $%.0f\n", top.MonthlyCost)
	fmt.Fprintf(r.w, "- CPU utilization: %.1f%%\n", topSR.AvgCPUUtilization*100)
	fmt.Fprintf(r.w, "- Memory utilization: %.1f%%\n", topSR.AvgMemUtilization*100)
	fmt.Fprintf(r.w, "- Resource balance: %.2f\n", topSR.Fragmentation.ResourceBalanceScore)

	if top.CostVsBaseline < 0 {
		fmt.Fprintf(r.w, "- Savings vs baseline: %.1f%%\n", -top.CostVsBaseline)
	}
	if top.AnnualSavings > 0 {
		fmt.Fprintf(r.w, "- Estimated annual savings: $%.0f\n", top.AnnualSavings)
	}

	if len(top.Warnings) > 0 {
		fmt.Fprintf(r.w, "\n### Warnings\n\n")
		for _, w := range top.Warnings {
			fmt.Fprintf(r.w, "- %s\n", w)
		}
	}

	fmt.Fprintf(r.w, "\n---\n*Generated by ClusterFit*\n")
	return nil
}
