package report

import (
	"bytes"
	"context"
	"encoding/json"
	"strings"
	"testing"
	"time"

	"github.com/guimove/clusterfit/internal/model"
)

func sampleRecs() []model.Recommendation {
	return []model.Recommendation{
		{
			Rank:         1,
			MonthlyCost:  1200,
			OverallScore: 85.5,
			SimulationResult: model.SimulationResult{
				InstanceConfig: model.InstanceConfig{
					InstanceTypes: []model.NodeTemplate{{InstanceType: "m5.xlarge"}},
					Strategy:      "homogeneous",
				},
				TotalNodes:        10,
				TotalCost:         1200,
				AvgCPUUtilization: 0.65,
				AvgMemUtilization: 0.72,
				Fragmentation:     model.FragmentationReport{ResourceBalanceScore: 0.92},
			},
			Rationale: "Good balance of cost and utilization",
		},
		{
			Rank:         2,
			MonthlyCost:  1400,
			OverallScore: 78.2,
			SimulationResult: model.SimulationResult{
				InstanceConfig: model.InstanceConfig{
					InstanceTypes: []model.NodeTemplate{{InstanceType: "c5.2xlarge"}},
					Strategy:      "homogeneous",
				},
				TotalNodes:        6,
				TotalCost:         1400,
				AvgCPUUtilization: 0.55,
				AvgMemUtilization: 0.48,
				Fragmentation:     model.FragmentationReport{ResourceBalanceScore: 0.78},
			},
		},
	}
}

func sampleMeta() ReportMeta {
	return ReportMeta{
		ClusterName:  "test-cluster",
		Region:       "us-east-1",
		CollectedAt:  time.Now(),
		WindowStart:  time.Now().Add(-7 * 24 * time.Hour),
		WindowEnd:    time.Now(),
		Percentile:   0.95,
		TotalPods:    150,
		TotalDaemons: 5,
	}
}

func TestTableReporter(t *testing.T) {
	var buf bytes.Buffer
	reporter := &TableReporter{w: &buf}

	err := reporter.Report(context.Background(), sampleRecs(), sampleMeta())
	if err != nil {
		t.Fatal(err)
	}

	output := buf.String()

	if !strings.Contains(output, "ClusterFit Recommendations") {
		t.Error("missing header")
	}
	if !strings.Contains(output, "test-cluster") {
		t.Error("missing cluster name")
	}
	if !strings.Contains(output, "m5.xlarge") {
		t.Error("missing instance type")
	}
	if !strings.Contains(output, "Recommended:") {
		t.Error("missing recommended section")
	}
}

func TestTableReporter_Empty(t *testing.T) {
	var buf bytes.Buffer
	reporter := &TableReporter{w: &buf}

	err := reporter.Report(context.Background(), nil, sampleMeta())
	if err != nil {
		t.Fatal(err)
	}

	if !strings.Contains(buf.String(), "No recommendations") {
		t.Error("expected 'No recommendations' message")
	}
}

func TestJSONReporter(t *testing.T) {
	var buf bytes.Buffer
	reporter := &JSONReporter{w: &buf}

	err := reporter.Report(context.Background(), sampleRecs(), sampleMeta())
	if err != nil {
		t.Fatal(err)
	}

	// Verify valid JSON
	var result map[string]interface{}
	if err := json.Unmarshal(buf.Bytes(), &result); err != nil {
		t.Fatalf("invalid JSON: %v", err)
	}

	if _, ok := result["meta"]; !ok {
		t.Error("missing 'meta' key")
	}
	if _, ok := result["recommendations"]; !ok {
		t.Error("missing 'recommendations' key")
	}
}

func TestMarkdownReporter(t *testing.T) {
	var buf bytes.Buffer
	reporter := &MarkdownReporter{w: &buf}

	err := reporter.Report(context.Background(), sampleRecs(), sampleMeta())
	if err != nil {
		t.Fatal(err)
	}

	output := buf.String()

	if !strings.Contains(output, "# ClusterFit Recommendations") {
		t.Error("missing markdown header")
	}
	if !strings.Contains(output, "| Rank |") {
		t.Error("missing markdown table")
	}
	if !strings.Contains(output, "## Top Recommendation") {
		t.Error("missing top recommendation section")
	}
	if !strings.Contains(output, "Generated by ClusterFit") {
		t.Error("missing footer")
	}
}

func TestNewReporter(t *testing.T) {
	var buf bytes.Buffer

	r := NewReporter("json", &buf)
	if _, ok := r.(*JSONReporter); !ok {
		t.Error("expected JSONReporter for 'json'")
	}

	r = NewReporter("markdown", &buf)
	if _, ok := r.(*MarkdownReporter); !ok {
		t.Error("expected MarkdownReporter for 'markdown'")
	}

	r = NewReporter("table", &buf)
	if _, ok := r.(*TableReporter); !ok {
		t.Error("expected TableReporter for 'table'")
	}

	r = NewReporter("unknown", &buf)
	if _, ok := r.(*TableReporter); !ok {
		t.Error("expected TableReporter as default")
	}
}
